# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='myuser/avatars/'),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Phone'),
        ),
    ]
