# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_auto_20160326_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/avatars/'),
        ),
    ]
