# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_extuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='is_admin',
        ),
    ]
